### ISSUE TITLE
Could you explain the effect of Pos and Neg prompts of each experts?

### ISSUE THREAD

**Issue by SLAPaper** [segmind/segmoe#20]
i.e. How do the prompts relate to the gates?

For example:

- If I want an expert to be more important, should I tune the prompt accordingly, how?
- If I know some expert is good/bad at some subject, should I tune the prompt accordingly, how?

**Comment by Warlord-K** [comment]
You should provide a positive and negative prompt which the Expert is good at, for example, If you have an expert that does well on realistic photos, keywords like realism should be in the positive prompt and keywords such as drawing, painting should be in negative prompt. I hope this clears up the confusion.

**Comment by SLAPaper** [comment]
Thank you, that's clear enough
