### ISSUE TITLE
Thank you! + model suggestion

### ISSUE THREAD

**Issue by C00reNUT** [segmind/segmoe#6]
Really nice results, thank you! If you could manage to get 4 models + LORAs into 24GB VRAM, that would be great.

Just a small suggestion to include DPO finetuned models as https://civitai.com/models/239624/opendallev11 and https://civitai.com/models/239836?modelVersionId=270839 they are much better at prompt following.

**Comment by Warlord-K** [comment]
Thanks! We are working on optimizing memory for the SegMoE models.

As for using civit models, you can also create your own models with the framework, just pass in the model download link in the config and the SegMoE will be created, let me know if you face any issue with that
